site_name: tt的个人网站
theme:
  name: material
  features:
    - navigation.indexes
site_url: https://ttxian.github.io
nav:
  - Home: 'index.md'
  - Games101学习笔记:
    - Lecture 1: 'Games101/Lecture - 1 Introduction.md'
    - Lecture 2: 'Games101/Lecture - 2 Review of linear algebra.md'
    - Lecture 3 & 4: 'Games101/Lecture - 3 Transformation.md'
    - Lecture 5 & 6: 'Games101/Lecture - 5 and 6 Rasteriazation (Triangles).md'
    - Lecture 7: 'Games101/Lecture - 7 shading.md'
    - Lecture 8: 'Games101/Lecture - 8 shading 渲染管线.md'
    - Lecture 9: 'Games101/Lecture - 9 Texture Mapping 纹理映射.md'
    - Lecture 10: 'Games101/Lecture - 10 Geometry 几何 Introduction.md'
    - Lecture 11: 'Games101/Lecture - 11 Geometry 曲线和平面 Curves and Surface.md'
    - Lecture 12: 'Games101/Lecture - 12 Geometry3 曲面.md'
    - Lecture 13: 'Games101/Lecture - 13 Ray tracing 光线追踪 技术难题.md'
    - Lecture 14: 'Games101/Lecture - 14 Ray tracing 光线追踪 加速结构.md'
    - Lecture 15: 'Games101/Lecture - 15 Ray tracing 辐射度量学.md'
    - Lecture 16: 'Games101/Lecture - 16 Ray tracing 蒙特卡洛积分.md'
    - Lecture 17: 'Games101/Lecture - 17 Materials and Appearance 材质和外观.md'
    - Lecture 18: 'Games101/Lecture - 18 现有材质研究.md'
    - Lecture 19: 'Games101/Lecture - 19 相机、镜头和光场.md'
    - Lecture 20: 'Games101/Lecture - 20 Color and Perception 颜色与感知.md'
  - Games101作业笔记:
    - 基础配置: 'Games101/作业/基础配置相关【卡顿】.md'
    - Homework3: 'Games101/作业/作业3相关.md'
    - Homework5: 'Games101/作业/作业5相关.md'
    - Homework6: 'Games101/作业/作业6相关.md'
    - Homework7: 'Games101/作业/作业7相关.md'


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
